# Generated by Django 4.0.6 on 2022-07-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analaytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='os',
            field=models.CharField(choices=[['window', 'window'], ['linux', 'linux'], ['iphone', 'iphone'], ['android', 'android'], ['Mac', 'Mac']], max_length=50),
        ),
    ]
