# Generated by Django 4.0.6 on 2022-07-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analaytics', '0002_visitor_ip_address_alter_visitor_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country_code3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='isp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='os',
            field=models.CharField(choices=[['Android', 'Android'], ['Iphone', 'Iphone'], ['Window', 'Window'], ['Linux', 'Linux'], ['Mac', 'Mac'], ['Other', 'Other']], max_length=50),
        ),
    ]
